// GENERATED by tools/gen_scotopic_weights.py. DO NOT EDIT.
// Regenerate: python3 tools/gen_scotopic_weights.py
//
// The Purkinje shift's two constant vectors (spec 11.83). One is derived and
// one is chosen, and the generator's header explains which is which -- read it
// before changing either.

// How strongly the RODS respond to each sRGB primary. DERIVED from published
// V'(lambda)/V(lambda) at each primary's dominant wavelength, times that
// primary's photopic weight, normalised to sum to exactly 1.
//
// Summing to 1 is what keeps grey at its own brightness: a neutral pixel's
// scotopic luminance equals its photopic one, so fading the effect in does not
// look like an exposure change.
//
// Red is 0.7% against its photopic 21.3%, and that number is not tuned --
// V'(610) is 0.016 where V(610) is 0.503. It is the whole "reds go near-black"
// half of the effect, and it falls out.
//
// ANCHOR: these weights reproduce the display white's published scotopic/photopic
// ratio at 2.36 against a literature ~2.4, which is what makes a wrong
// coefficient loud rather than merely a different blue.
const vec3 PURKINJE_SCOTOPIC_W = vec3(0.00711, 0.36516, 0.62773);

// What that achromatic rod signal is PERCEIVED as. CHOSEN, with one physical
// constraint enforced by the generator: dot(tint, photopic luma) == 1 exactly,
// so the tint moves hue and never brightness.
//
// This is not an approximation of Kirk & O'Brien's per-cone injection -- it is
// algebraically identical to it. Rods are monochromats, so the LMS round trip
// of a scalar collapses into exactly one constant vector.
const vec3 PURKINJE_ROD_TINT = vec3(0.83952, 1.00942, 1.37921);
