set(CMAKE_INSTALL_RPATH "${EXTERNAL_INSTALL_LOCATION}/lib")
set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)

set(EXTERNAL_INSTALL_LOCATION ${CMAKE_BINARY_DIR}/external)

# Find the required libraries
find_library(GLFW_LIBRARY NAMES glfw3 PATHS "${EXTERNAL_INSTALL_LOCATION}/lib" NO_DEFAULT_PATH)
message(STATUS "GLFW Library found at: ${GLFW_LIBRARY}")

find_library(CGLM_LIBRARY NAMES cglm libcglm PATHS ${EXTERNAL_INSTALL_LOCATION}/lib NO_DEFAULT_PATH)
message(STATUS "CGLM Library found at: ${CGLM_LIBRARY}")

message(STATUS "Looking for ASSIMP in: ${EXTERNAL_INSTALL_LOCATION}/lib")
find_library(ASSIMP_LIBRARY NAMES assimp PATHS "${EXTERNAL_INSTALL_LOCATION}/lib" NO_DEFAULT_PATH)
message(STATUS "ASSIMP Library found at: ${ASSIMP_LIBRARY}")

# Set these variables in your main CMakeLists.txt
set(GLFW_LIBRARY NAMES assimp ${GLFW_LIBRARY} CACHE INTERNAL "GLFW library")
set(CGLM_LIBRARY NAMES cglm ${CGLM_LIBRARY} CACHE INTERNAL "CGLM library")
set(ASSIMP_LIBRARY ${ASSIMP_LIBRARY} CACHE INTERNAL "ASSIMP library")

