"""The engine's own source as one number, for keys that must not outlive the code that made what
they name (spec 13.42): a cooked capture is the engine's arithmetic run over a scene, so an edit to
any file the build digests leaves every cooked capture unfindable. The files are the build's own
list, so what is digested is exactly what the header depends on."""
import argparse
import hashlib
import os

from gen_shader_header import write_if_changed

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('root', help='the engine directory, which names are hashed relative to')
    parser.add_argument('out', help='the header to write')
    parser.add_argument('files', nargs='+', help='every file digested')
    args = parser.parse_args()
    # Sorted, and named relative to the root with forward slashes, so the number is the same in
    # any checkout on any platform.
    names = sorted(os.path.relpath(f, args.root).replace(os.sep, '/') for f in args.files)
    digest = hashlib.sha256()
    for rel in names:
        digest.update(rel.encode('utf-8') + b'\0')
        with open(os.path.join(args.root, rel), 'rb') as f:
            digest.update(f.read())
        digest.update(b'\0')
    # Written only when it changed, so an unchanged source rebuilds nothing that includes it.
    write_if_changed(args.out,
                     '// Generated by gen_build_digest.py: the engine\'s own source as one number.\n'
                     '#define CETRA_BUILD_DIGEST 0x%sULL\n' % digest.hexdigest()[:16])

if __name__ == '__main__':
    main()
