import argparse
import hashlib
import os

# The engine's own source as one number, for keys that must not outlive the code that made what
# they name (spec 13.42): a cooked capture is the engine's arithmetic run over a scene, so an edit
# anywhere in it leaves every cooked capture unfindable. Over the library's own sources and its
# shaders, not the vendored libraries under src/ext, which change only by a submodule bump.
SOURCE_DIRS = ['src', 'src/game', 'src/procedural']
SOURCE_EXTENSIONS = ('.c', '.h', '.cpp')

def digested_files(root):
    files = []
    for rel in SOURCE_DIRS:
        folder = os.path.join(root, rel)
        for name in os.listdir(folder):
            if name.endswith(SOURCE_EXTENSIONS):
                files.append(os.path.join(rel, name))
    for folder, _, names in os.walk(os.path.join(root, 'shaders')):
        for name in names:
            if name.endswith('.glsl'):
                files.append(os.path.relpath(os.path.join(folder, name), root))
    # Sorted, and named relative to the root with forward slashes, so the number is the same in
    # any checkout on any platform.
    return sorted(f.replace(os.sep, '/') for f in files)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('root', help='the engine directory, holding src and shaders')
    parser.add_argument('out', help='the header to write')
    args = parser.parse_args()
    digest = hashlib.sha256()
    for rel in digested_files(args.root):
        digest.update(rel.encode('utf-8') + b'\0')
        with open(os.path.join(args.root, rel), 'rb') as f:
            digest.update(f.read())
        digest.update(b'\0')
    text = ('// Generated by gen_build_digest.py: the engine\'s own source as one number.\n'
            '#define CETRA_BUILD_DIGEST 0x%sULL\n' % digest.hexdigest()[:16])
    # Written only when it changed, so an unchanged source rebuilds nothing that includes it.
    try:
        with open(args.out, 'r') as f:
            if f.read() == text:
                return
    except OSError:
        pass
    with open(args.out, 'w') as f:
        f.write(text)

if __name__ == '__main__':
    main()
