// Generated by apps/silent/tools/make_cards.py -- do not edit; rerun it.
#ifndef _SILENT_CARDS_H_
#define _SILENT_CARDS_H_

// The cards in cards_albedo.png.
typedef enum {
    CARD_NOTE,
    CARD_LETTER,
    CARD_PHOTO_LAKE,
    CARD_PHOTO_PARK,
    CARD_PHOTO_GARDEN,
    CARD_PHOTO_ROAD,
    CARD_PHOTO_TREE,
    CARD_PHOTO_SNOW,
    CARD_CLOCK_DIAL,
    CARD_CLOCK_PANEL,
    CARD_CLOCK_FRIEZE,
    CARD_COUNT
} CardId;

typedef struct CardSpec {
    float uv[4];   // {u0, v0, u1, v1}, V up
    float size[2]; // metres: width, height
} CardSpec;

static const CardSpec CARDS[CARD_COUNT] = {
    [CARD_NOTE] = {{0.783203f, 0.589844f, 0.929688f, 1.000000f}, {0.1000f, 0.1400f}},
    [CARD_LETTER] = {{0.265625f, 0.419922f, 0.470703f, 1.000000f}, {0.2100f, 0.2970f}},
    [CARD_PHOTO_LAKE] = {{0.470703f, 0.330078f, 0.617188f, 0.525391f}, {0.1500f, 0.1000f}},
    [CARD_PHOTO_PARK] = {{0.617188f, 0.330078f, 0.763672f, 0.525391f}, {0.1500f, 0.1000f}},
    [CARD_PHOTO_GARDEN] = {{0.265625f, 0.218750f, 0.412109f, 0.414062f}, {0.1500f, 0.1000f}},
    [CARD_PHOTO_ROAD] = {{0.783203f, 0.291016f, 0.880859f, 0.583984f}, {0.1000f, 0.1500f}},
    [CARD_PHOTO_TREE] = {{0.880859f, 0.322266f, 0.988281f, 0.583984f}, {0.0880f, 0.1070f}},
    [CARD_PHOTO_SNOW] = {{0.412109f, 0.128906f, 0.558594f, 0.324219f}, {0.1500f, 0.1000f}},
    [CARD_CLOCK_DIAL] = {{0.000000f, 0.234375f, 0.265625f, 1.000000f}, {0.3400f, 0.4900f}},
    [CARD_CLOCK_PANEL] = {{0.470703f, 0.531250f, 0.783203f, 1.000000f}, {0.4000f, 0.3000f}},
    [CARD_CLOCK_FRIEZE] = {{0.558594f, 0.207031f, 0.964844f, 0.285156f}, {0.5200f, 0.0500f}},
};

// Metres from the card's lower left.
static const float CARD_CLOCK_DIAL_HANDS[2] = {0.1700f, 0.1700f};

// Metres from the card's lower left.
static const float CARD_CLOCK_DIAL_SECONDS[2] = {0.1700f, 0.2188f};

#endif // _SILENT_CARDS_H_
