// Generated by apps/silent/tools/make_cards.py -- do not edit; rerun it.
#ifndef _SILENT_CARDS_H_
#define _SILENT_CARDS_H_

// The cards in cards_albedo.png.
typedef enum {
    CARD_NOTE,
    CARD_LETTER,
    CARD_PHOTO_LAKE,
    CARD_PHOTO_PARK,
    CARD_PHOTO_GARDEN,
    CARD_PHOTO_ROAD,
    CARD_PHOTO_TREE,
    CARD_PHOTO_SNOW,
    CARD_COUNT
} CardId;

typedef struct CardSpec {
    float uv[4];   // {u0, v0, u1, v1}, V up
    float size[2]; // metres: width, height
} CardSpec;

static const CardSpec CARDS[CARD_COUNT] = {
    [CARD_NOTE] = {{0.410156f, 0.589844f, 0.703125f, 1.000000f}, {0.1000f, 0.1400f}},
    [CARD_LETTER] = {{0.000000f, 0.419922f, 0.410156f, 1.000000f}, {0.2100f, 0.2970f}},
    [CARD_PHOTO_LAKE] = {{0.410156f, 0.388672f, 0.703125f, 0.583984f}, {0.1500f, 0.1000f}},
    [CARD_PHOTO_PARK] = {{0.703125f, 0.238281f, 0.996094f, 0.433594f}, {0.1500f, 0.1000f}},
    [CARD_PHOTO_GARDEN] = {{0.000000f, 0.218750f, 0.292969f, 0.414062f}, {0.1500f, 0.1000f}},
    [CARD_PHOTO_ROAD] = {{0.703125f, 0.707031f, 0.898438f, 1.000000f}, {0.1000f, 0.1500f}},
    [CARD_PHOTO_TREE] = {{0.703125f, 0.439453f, 0.917969f, 0.701172f}, {0.0880f, 0.1070f}},
    [CARD_PHOTO_SNOW] = {{0.292969f, 0.187500f, 0.585938f, 0.382812f}, {0.1500f, 0.1000f}},
};

#endif // _SILENT_CARDS_H_
