// Generated by apps/silent/tools/make_cat_blender.py -- do not edit; rerun it.
#ifndef _SILENT_CAT_CLIPS_H_
#define _SILENT_CAT_CLIPS_H_

// The clips in assets/models/cat.glb, by the names the file gives them.
typedef enum {
    CAT_CLIP_IDLE,
    CAT_CLIP_WALK,
    CAT_CLIP_SIT_DOWN,
    CAT_CLIP_STAND_UP,
    CAT_CLIP_SIT,
    CAT_CLIP_LIE_DOWN,
    CAT_CLIP_SIT_UP,
    CAT_CLIP_LIE,
    CAT_CLIP_CURL_UP,
    CAT_CLIP_UNCURL,
    CAT_CLIP_SLEEP,
    CAT_CLIP_MEOW_SHORT,
    CAT_CLIP_MEOW_LONG,
    CAT_CLIP_BLINK,
    CAT_CLIP_TROT,
    CAT_CLIP_STAIR_UP,
    CAT_CLIP_STAIR_DOWN,
    CAT_CLIP_TURN_L90,
    CAT_CLIP_TURN_R90,
    CAT_CLIP_JUMP_UP,
    CAT_CLIP_JUMP_DOWN,
    CAT_CLIP_COUNT
} CatClipId;

typedef struct CatClipEvent {
    const char* name;
    float seconds; // from the clip's start
} CatClipEvent;

typedef struct CatClipSpec {
    const char* name;
    float seconds;
    int looping;
    float travel; // metres forward, model space, from first frame to last
    int event_count;
    CatClipEvent events[6];
} CatClipSpec;

static const CatClipSpec CAT_CLIPS[CAT_CLIP_COUNT] = {
    [CAT_CLIP_IDLE] = {"idle", 4.0000f, 1, 0.0000f, 0, {{0}}},
    [CAT_CLIP_WALK] =
        {"walk",
         0.8000f,
         1,
         0.4400f,
         4,
         {{"paw_lh", 0.0200f}, {"paw_lf", 0.2200f}, {"paw_rh", 0.4200f}, {"paw_rf", 0.6200f}}},
    [CAT_CLIP_SIT_DOWN] = {"sit_down", 0.8000f, 0, 0.0000f, 0, {{0}}},
    [CAT_CLIP_STAND_UP] = {"stand_up", 0.8000f, 0, 0.0000f, 0, {{0}}},
    [CAT_CLIP_SIT] = {"sit", 6.0000f, 1, 0.0000f, 0, {{0}}},
    [CAT_CLIP_LIE_DOWN] =
        {"lie_down", 1.0000f, 0, 0.0000f, 2, {{"paw_lf", 0.4500f}, {"paw_rf", 0.6800f}}},
    [CAT_CLIP_SIT_UP] = {"sit_up", 1.0000f, 0, 0.0000f, 0, {{0}}},
    [CAT_CLIP_LIE] = {"lie", 5.0000f, 1, 0.0000f, 0, {{0}}},
    [CAT_CLIP_CURL_UP] = {"curl_up", 1.6000f, 0, 0.0000f, 0, {{0}}},
    [CAT_CLIP_UNCURL] = {"uncurl", 1.6000f, 0, 0.0000f, 0, {{0}}},
    [CAT_CLIP_SLEEP] = {"sleep", 6.0000f, 1, 0.0000f, 0, {{0}}},
    [CAT_CLIP_MEOW_SHORT] = {"meow_short", 0.6000f, 0, 0.0000f, 1, {{"meow", 0.0800f}}},
    [CAT_CLIP_MEOW_LONG] = {"meow_long", 1.1000f, 0, 0.0000f, 1, {{"meow", 0.0800f}}},
    [CAT_CLIP_BLINK] = {"blink", 0.2500f, 0, 0.0000f, 0, {{0}}},
    [CAT_CLIP_TROT] =
        {"trot",
         0.5000f,
         1,
         0.6000f,
         4,
         {{"paw_lh", 0.0125f}, {"paw_rf", 0.0125f}, {"paw_rh", 0.2625f}, {"paw_lf", 0.2625f}}},
    [CAT_CLIP_STAIR_UP] =
        {"stair_up",
         0.8000f,
         1,
         0.5000f,
         4,
         {{"paw_lh", 0.0200f}, {"paw_lf", 0.2200f}, {"paw_rh", 0.4200f}, {"paw_rf", 0.6200f}}},
    [CAT_CLIP_STAIR_DOWN] =
        {"stair_down",
         0.8000f,
         1,
         0.5000f,
         4,
         {{"paw_lh", 0.0200f}, {"paw_lf", 0.2200f}, {"paw_rh", 0.4200f}, {"paw_rf", 0.6200f}}},
    [CAT_CLIP_TURN_L90] = {"turn_l90", 0.7000f, 0, 0.0000f, 0, {{0}}},
    [CAT_CLIP_TURN_R90] = {"turn_r90", 0.7000f, 0, 0.0000f, 0, {{0}}},
    [CAT_CLIP_JUMP_UP] =
        {"jump_up", 1.1000f, 0, 0.0000f, 2, {{"takeoff", 0.4200f}, {"land", 0.8000f}}},
    [CAT_CLIP_JUMP_DOWN] = {"jump_down",
                            1.1000f,
                            0,
                            0.0000f,
                            3,
                            {{"takeoff", 0.4000f}, {"land", 0.7200f}, {"land_hind", 0.8000f}}},
};

// Model space: x the cat's left, y up, z forward, the feet at y = 0.
#define CAT_EYE_X  0.0215f
#define CAT_EYE_Y  0.2790f
#define CAT_EYE_Z  0.2331f
#define CAT_HEAD_Y 0.2700f
#define CAT_HEAD_Z 0.1800f

#endif // _SILENT_CAT_CLIPS_H_
