// Generated by apps/silent/tools/make_gothic.py -- do not edit; rerun it.
#ifndef _SILENT_GOTHICS_H_
#define _SILENT_GOTHICS_H_

// The cards in gothic_albedo.png.
typedef enum {
    GOTHIC_PANEL_LINENFOLD,
    GOTHIC_PANEL_TRACERY,
    GOTHIC_FRIEZE,
    GOTHIC_RUG,
    GOTHIC_RUNNER,
    GOTHIC_RUNNER_END,
    GOTHIC_GLASS_ROSE,
    GOTHIC_GLASS_LILY,
    GOTHIC_GLASS_STAR,
    GOTHIC_SPINES_0,
    GOTHIC_SPINES_1,
    GOTHIC_SPINES_2,
    GOTHIC_SPINES_3,
    GOTHIC_COAT_OF_ARMS,
    GOTHIC_FIREBACK,
    GOTHIC_FLAME_A,
    GOTHIC_FLAME_B,
    GOTHIC_COUNT
} GothicId;

typedef struct GothicSpec {
    float uv[4];   // {u0, v0, u1, v1}, V up
    float size[2]; // metres: width, height
} GothicSpec;

static const GothicSpec GOTHICS[GOTHIC_COUNT] = {
    [GOTHIC_PANEL_LINENFOLD] = {{0.521484f, 0.634766f, 0.639648f, 1.000000f}, {0.5500f, 0.8500f}},
    [GOTHIC_PANEL_TRACERY] = {{0.639648f, 0.634766f, 0.757812f, 1.000000f}, {0.5500f, 0.8500f}},
    [GOTHIC_FRIEZE] = {{0.235352f, 0.162109f, 0.471680f, 0.230469f}, {1.1000f, 0.1591f}},
    [GOTHIC_RUG] = {{0.287109f, 0.375000f, 0.521484f, 1.000000f}, {3.0000f, 4.0000f}},
    [GOTHIC_RUNNER] = {{0.898438f, 0.488281f, 0.957031f, 0.644531f}, {0.7500f, 1.0000f}},
    [GOTHIC_RUNNER_END] = {{0.778320f, 0.441406f, 0.836914f, 0.488281f}, {0.7500f, 0.3000f}},
    [GOTHIC_GLASS_ROSE] = {{0.000000f, 0.316406f, 0.095703f, 1.000000f}, {0.7000f, 2.5000f}},
    [GOTHIC_GLASS_LILY] = {{0.095703f, 0.316406f, 0.191406f, 1.000000f}, {0.7000f, 2.5000f}},
    [GOTHIC_GLASS_STAR] = {{0.191406f, 0.316406f, 0.287109f, 1.000000f}, {0.7000f, 2.5000f}},
    [GOTHIC_SPINES_0] = {{0.521484f, 0.365234f, 0.764160f, 0.488281f}, {1.1833f, 0.3000f}},
    [GOTHIC_SPINES_1] = {{0.287109f, 0.236328f, 0.533203f, 0.359375f}, {1.2000f, 0.3000f}},
    [GOTHIC_SPINES_2] = {{0.533203f, 0.236328f, 0.777832f, 0.359375f}, {1.1929f, 0.3000f}},
    [GOTHIC_SPINES_3] = {{0.000000f, 0.187500f, 0.234863f, 0.310547f}, {1.1452f, 0.3000f}},
    [GOTHIC_COAT_OF_ARMS] = {{0.757812f, 0.734375f, 0.867188f, 1.000000f}, {0.7000f, 0.8500f}},
    [GOTHIC_FIREBACK] = {{0.757812f, 0.494141f, 0.898438f, 0.728516f}, {0.9000f, 0.7500f}},
    [GOTHIC_FLAME_A] = {{0.898438f, 0.828125f, 0.952148f, 1.000000f}, {0.5000f, 0.8000f}},
    [GOTHIC_FLAME_B] = {{0.898438f, 0.650391f, 0.952148f, 0.822266f}, {0.5000f, 0.8000f}},
};

// The spines in each strip: the edges between books, in metres from its left.
// Book i of a strip is between edges i and i + 1.
static const float GOTHIC_SPINES_0_EDGES[] = {
    0.0000f, 0.0310f, 0.0619f, 0.1143f, 0.1500f, 0.1738f, 0.2095f, 0.2548f,
    0.2929f, 0.3333f, 0.3548f, 0.3881f, 0.4452f, 0.4690f, 0.5024f, 0.5524f,
    0.5810f, 0.6286f, 0.6595f, 0.6929f, 0.7286f, 0.7833f, 0.8381f, 0.8881f,
    0.9310f, 0.9524f, 0.9976f, 1.0357f, 1.0595f, 1.1024f, 1.1524f, 1.1833f};
#define GOTHIC_SPINES_0_BOOKS 31
static const float GOTHIC_SPINES_1_EDGES[] = {
    0.0000f, 0.0500f, 0.1000f, 0.1500f, 0.1929f, 0.2500f, 0.2810f, 0.3024f, 0.3381f, 0.3857f,
    0.4429f, 0.4714f, 0.5048f, 0.5286f, 0.5762f, 0.6286f, 0.6571f, 0.6929f, 0.7333f, 0.7857f,
    0.8214f, 0.8738f, 0.9071f, 0.9286f, 0.9571f, 1.0143f, 1.0714f, 1.1071f, 1.1619f, 1.2000f};
#define GOTHIC_SPINES_1_BOOKS 29
static const float GOTHIC_SPINES_2_EDGES[] = {
    0.0000f, 0.0310f, 0.0524f, 0.0833f, 0.1381f, 0.1619f, 0.2071f, 0.2333f, 0.2619f,
    0.3143f, 0.3524f, 0.4024f, 0.4262f, 0.4667f, 0.4881f, 0.5190f, 0.5476f, 0.5857f,
    0.6095f, 0.6548f, 0.6952f, 0.7262f, 0.7476f, 0.7929f, 0.8333f, 0.8690f, 0.8929f,
    0.9143f, 0.9714f, 1.0262f, 1.0548f, 1.1000f, 1.1286f, 1.1667f, 1.1929f};
#define GOTHIC_SPINES_2_BOOKS 34
static const float GOTHIC_SPINES_3_EDGES[] = {
    0.0000f, 0.0571f, 0.1071f, 0.1667f, 0.1976f, 0.2357f, 0.2619f, 0.2929f,
    0.3357f, 0.3595f, 0.4095f, 0.4405f, 0.4738f, 0.5167f, 0.5714f, 0.6071f,
    0.6619f, 0.6905f, 0.7119f, 0.7381f, 0.7762f, 0.8071f, 0.8524f, 0.8810f,
    0.9238f, 0.9714f, 0.9929f, 1.0143f, 1.0405f, 1.0881f, 1.1452f};
#define GOTHIC_SPINES_3_BOOKS 30

#endif // _SILENT_GOTHICS_H_
