// Generated by apps/silent/tools/make_map.py -- do not edit; rerun it.
// Included by town_map.c alone: it defines the table town_map.h declares.
#ifndef _SILENT_MAP_ART_H_
#define _SILENT_MAP_ART_H_

const MapArt MAP_ART[MAP_COUNT] = {
    [MAP_TOWN] =
        {
            .print_file = "ui_town_map.png",
            .marks_file = "ui_town_map_marks.png",
            .print_size = {2048.000000f, 1536.000000f},
            .marks_size = {1024.000000f, 1024.000000f},
            .origin = {-127.000000f, -52.000000f},
            .at = {100.000000f, 96.000000f},
            .px_per_m = 6.794118f,
            .arrow_frames = 64,
            .arrow_cell = 80,
            .arrow_cols = 8,
            .mark_count = 3,
            .marks =
                {
                    {PLACE_BARRICADE,
                     {0.005859f, 0.630859f, 0.250000f, 0.777344f},
                     {250.000000f, 150.000000f},
                     {60.000000f, 90.000000f}},
                    {PLACE_ROAD_END,
                     {0.261719f, 0.630859f, 0.574219f, 0.806641f},
                     {320.000000f, 180.000000f},
                     {250.000000f, 120.000000f}},
                    {PLACE_CABIN,
                     {0.585938f, 0.630859f, 0.878906f, 0.787109f},
                     {300.000000f, 160.000000f},
                     {70.000000f, 82.000000f}},
                },
            .folded_front = {0.000000f, 0.000000f, 0.500000f, 1.000000f},
            .folded_back = {0.500000f, 0.000000f, 1.000000f, 1.000000f},
            .seed = 7u,
        },
};

#endif // _SILENT_MAP_ART_H_
