#!/usr/bin/env python3
"""Generate the IES photometric fixture (spec 11.57): four .ies files and a scene.

Every candela in these files is known BY CONSTRUCTION -- each is a closed-form
function of its two angles, written out by the same expression the checks below
re-evaluate. That is the whole design: an IES reader cannot be tested against a
picture, because a table resampled off the wrong plane or folded with a modulo
where LM-63 mirrors still lights a room plausibly. It also cannot be tested
against a real .ies file, because nobody knows what a real luminaire's candela
at 37.5 degrees ought to be. Ground truth here is PAINTED, not measured.

The tool is imported and run rather than reimplemented, the gen_hair_fixture.py
pattern: assets/gen_hair_fixture.py says "the fixture verifies the tool rather
than trusting it", and the same holds twice over here, because the C reader in
cetra/src/ies.c is a THIRD implementation of the same parse. The gate reads
--ies-probe and compares against these same closed forms, so tool, reader and
shader are all held to one arithmetic nobody can quietly edit.

THE FOUR FILES, and the question only each one answers:

  ies_symmetric.ies   ONE horizontal plane -- the rotationally symmetric case,
                      which is most real downlights. A cosine lobe, so every tap
                      has an exact expected value, and the 90 degree tail is
                      exactly zero, which is what pbr_frag's early-out needs.
  ies_bilateral.ies   Horizontal angles 0..180, declaring BILATERAL symmetry. The
                      case a modulo fold gets wrong: 190 degrees must mirror to
                      170, not wrap to 10, and only an asymmetric horizontal ramp
                      can tell those apart.
  ies_quadrant.ies    Horizontal angles 0..90, declaring QUADRANT symmetry -- the
                      second mirror, and the one whose span the reader has to
                      read off the declaration rather than guess from the values.
  ies_asymmetric.ies  Horizontal angles all the way to 360, declaring NO symmetry.
                      Nothing is mirrored, so a reader that assumed a mirror
                      renders the far half backwards.

The scene names the symmetric one on a point light with NO authored intensity,
which is what exercises the peak-seeding path: the light must come out at the
file's own peak candela.

Regenerate with: python3 assets/gen_ies_fixture.py
"""

import importlib.util
import json
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))

# The vertical grids are 10 and 5 degree steps, which is what real LM-63 files
# carry -- deliberately BELOW the engine's 32-tap ceiling on the symmetric file
# and above it on none of them, so the resample is never asked to invent detail.
VERT_STEP = 10.0
PEAK_CD = 1200.0


def lobe(v_deg, tail=0.0):
    """Vertical falloff: a cosine lobe to 90 degrees, `tail` at the edge.

    Exactly zero matters. pbr_frag skips nine shadow taps and the whole GGX chain
    on `attenuation <= 0.0`, and its comment records that this is only safe
    because every factor reaches zero EXACTLY -- so a profile whose tail merely
    got small would silently change which fragments take that path.

    Which is why `tail` exists and why one file sets it. A file painting a literal
    0 arrives as 0/peak = 0 and reads back exactly zero with the SNAP DELETED from
    both readers -- so four files that all do that measure the arithmetic and never
    the guarantee. A residual below the snap threshold is the only input that does.
    """
    if v_deg >= 90.0:
        return tail
    return math.cos(math.radians(v_deg))


def ramp(h_deg, span):
    """Horizontal falloff: linear from 1 at h=0 to 0 at h=span.

    Monotone across the whole sweep on purpose. A symmetric or periodic function
    would read the same whether the reader mirrored or wrapped, which is exactly
    the confusion the bilateral and quadrant files exist to detect.
    """
    return 1.0 - h_deg / span


def candela(v_deg, h_deg, span, tail=0.0):
    return PEAK_CD * lobe(v_deg, tail) * ramp(h_deg, span)


def write_ies(path, horiz, span, note, tail=0.0):
    """One LM-63 file. Horizontal-major candela, as the standard orders them."""
    verts = [i * VERT_STEP for i in range(int(90.0 / VERT_STEP) + 1)]
    lines = [
        "IESNA:LM-63-2002",
        "[TEST] %s" % note,
        "[MORE] generated by assets/gen_ies_fixture.py; candela are closed-form",
        "TILT=NONE",
        # lamps, lumens, multiplier, n_vert, n_horiz, photometric type, units, w, l, h
        "1 %g 1 %d %d 1 1 0.5 0.5 0.5" % (PEAK_CD, len(verts), len(horiz)),
        "1 1 100",  # ballast, future, input watts
        " ".join("%g" % v for v in verts),
        " ".join("%g" % h for h in horiz),
    ]
    for h in horiz:
        lines.append(" ".join("%.6g" % candela(v, h, span, tail) for v in verts))
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    return verts


# name, horizontal angles, declared span, note, residual tail (relative to peak)
FILES = [
    ("ies_symmetric.ies", [0.0], 360.0, "rotationally symmetric downlight", 0.0),
    ("ies_bilateral.ies", [0.0, 45.0, 90.0, 135.0, 180.0], 180.0, "bilateral wall-washer",
     0.0),
    ("ies_quadrant.ies", [0.0, 30.0, 60.0, 90.0], 90.0, "quadrant-symmetric luminaire", 0.0),
    ("ies_asymmetric.ies", [0.0, 60.0, 120.0, 180.0, 240.0, 300.0, 360.0], 360.0,
     "fully asymmetric luminaire", 0.0),
    # A real cutoff luminaire's tail is small, not absent -- stray light off the
    # reflector, measured and reported. The four above paint a literal 0 and so
    # test the arithmetic that carries it; this one is the only input the SNAP in
    # ies.c and gen_ies_table.py acts on, and therefore the only one that can
    # tell an enforced exact zero from an inherited one.
    ("ies_tinytail.ies", [0.0], 360.0, "cutoff luminaire with a residual tail", 1e-9),
]

for name, horiz, span, note, tail in FILES:
    write_ies(os.path.join(HERE, name), horiz, span, note, tail)

# ---- run the real tool over them, and check it against what we painted -------
#
# spec_from_file_location rather than a plain import: tools/ is not a package and
# is not on the path. gen_hair_fixture.py does the same, and run_fixture_gen_gate
# symlinks tools/ into its scratch tree precisely so this keeps working there.
_spec = importlib.util.spec_from_file_location(
    "gen_ies_table", os.path.join(HERE, os.pardir, "tools", "gen_ies_table.py"))
_tool = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_tool)

for name, horiz, span, note, tail in FILES:
    table, meta = _tool.load(os.path.join(HERE, name))
    symmetric = len(horiz) == 1

    assert meta["symmetric"] == symmetric, \
        "%s: symmetry read as %s, declared %s" % (name, meta["symmetric"], symmetric)
    assert abs(meta["span"] - span) < 1e-6, \
        "%s: span read as %g, declared %g" % (name, meta["span"], span)
    assert abs(meta["peak_cd"] - PEAK_CD) < 1e-3, \
        "%s: peak read as %g, constructed %g" % (name, meta["peak_cd"], PEAK_CD)
    assert meta["h_taps"] == (1 if symmetric else len(horiz)), \
        "%s: %d horizontal taps for %d planes" % (name, meta["h_taps"], len(horiz))

    # Every tap against the closed form. The table is normalised, so the
    # comparison is candela/peak -- which is also the identity the engine leans
    # on when it seeds a light's intensity from peak_cd.
    for iv in range(meta["v_taps"]):
        v = meta["v_lo"] + (meta["v_hi"] - meta["v_lo"]) * iv / (meta["v_taps"] - 1)
        for ih in range(meta["h_taps"]):
            h = 0.0 if meta["h_taps"] == 1 else span * ih / (meta["h_taps"] - 1)
            want = candela(v, h, span, tail) / PEAK_CD
            if v >= 90.0 - 1e-9:
                want = 0.0  # the snap: a residual below 1e-6 becomes an exact zero
            got = table[iv * meta["h_taps"] + ih]
            assert abs(got - want) < 1e-5, \
                "%s: tap v=%g h=%g read %.6f, constructed %.6f" % (name, v, h, got, want)

    # The tail is EXACTLY zero, not merely small (see lobe()).
    for ih in range(meta["h_taps"]):
        tail = table[(meta["v_taps"] - 1) * meta["h_taps"] + ih]
        assert tail == 0.0, "%s: 90 degree tail is %r, not exactly 0.0" % (name, tail)

# The MIRROR, which is the property a modulo fold would pass every check above
# and still get wrong -- every tap sampled so far lies inside [0, span], where
# the two agree. 190 degrees must reflect to 170, not wrap to 10.
for span, probe, want in ((180.0, 190.0, 170.0), (180.0, 350.0, 10.0),
                          (90.0, 100.0, 80.0), (90.0, 170.0, 10.0),
                          (360.0, 350.0, 350.0)):
    got = _tool.fold_horizontal(probe, span)
    assert abs(got - want) < 1e-9, \
        "fold(%g, span %g) = %g, want %g (a modulo would give %g)" % (
            probe, span, got, want, probe % span)

# ---- the scene ---------------------------------------------------------------
#
# NO authored intensity on purpose: absent, the loader must seed it from the
# file's own peak candela, so the light comes out at PEAK_CD. That is the path
# that makes normalising lossless, and a scene authoring a number would hide it.
CSCN = {
    "version": 1,
    "models": [{"path": "contact_local_bare.gltf"}],
    "environment": {"ambient": [0.02, 0.02, 0.024]},
    "lights": [{
        "name": "ies_lamp",
        "type": "point",
        "position": [0.0, 2.0, 0.0],
        "color": [1.0, 1.0, 1.0],
        "range": 12.0,
        "profile": "ies_symmetric.ies",
    }],
    "camera": {"eye": [0.0, 1.9, 4.4], "target": [0.0, 0.25, 0.0], "fov": 42},
    "post": {"tonemap": "neutral", "exposure": 1.0},
}
with open(os.path.join(HERE, "ies_fixture.cscn"), "w") as fh:
    json.dump(CSCN, fh, indent=1)
    fh.write("\n")

print("wrote %d .ies files and ies_fixture.cscn (peak %.0f cd, every tap checked "
      "against its closed form)" % (len(FILES), PEAK_CD))
