#!/usr/bin/env python3
"""Convert the vendored LTC lookup tables into a C header.

Source: tools/ltc_data.js -- verbatim copy of fit/results/ltc.js from
selfshadow/ltc_code @ 31e5e96b54f98f33098f8503003119ba2231a1c6 (BSD 3-clause,
see tools/LTC_LICENSE). The file defines two 64x64x4 float arrays in order:
g_ltc_1 (inverse-M matrix fit) then g_ltc_2 (magnitude/Fresnel/sphere tables).

Run once; the output header is checked in and builds never regenerate:
    python3 tools/gen_ltc_lut.py

Element order is preserved verbatim -- the ltc_code WebGL demo uploads this
exact order via texImage2D and samples with uv = (roughness, sqrt(1-NdotV)),
which is the convention cetra/shaders/include/ltc.glsl copies.
"""

import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "tools", "ltc_data.js")
DST = os.path.join(REPO, "cetra", "src", "ltc_lut.h")
DIM = 64
COUNT = DIM * DIM * 4
UPSTREAM = "selfshadow/ltc_code @ 31e5e96b54f98f33098f8503003119ba2231a1c6"


def extract_arrays(text):
    """Return the bracketed float blocks in file order."""
    arrays = []
    for m in re.finditer(r"var\s+\w+\s*=\s*\[(.*?)\]", text, re.DOTALL):
        floats = [float(t) for t in re.findall(r"[-+0-9.eE]+", m.group(1))]
        arrays.append(floats)
    return arrays


def c_float(v):
    """%.9g preserves float32 round-trip, but bare integers ("1") need a
    decimal point before the f suffix to be valid C."""
    s = "%.9g" % v
    if "." not in s and "e" not in s and "E" not in s:
        s += ".0"
    return s + "f"


def emit_array(out, name, values):
    out.write("static const float %s[%d * %d * 4] = {\n" % (name, DIM, DIM))
    for i in range(0, len(values), 4):
        row = ", ".join(c_float(v) for v in values[i : i + 4])
        out.write("    %s,\n" % row)
    out.write("};\n")


def main():
    with open(SRC) as f:
        arrays = extract_arrays(f.read())
    if len(arrays) != 2:
        sys.exit("expected 2 arrays in %s, found %d" % (SRC, len(arrays)))
    for i, arr in enumerate(arrays):
        if len(arr) != COUNT:
            sys.exit("array %d has %d floats, expected %d" % (i, len(arr), COUNT))

    with open(DST, "w") as out:
        out.write("/* GENERATED by tools/gen_ltc_lut.py from tools/ltc_data.js\n")
        out.write(" * (%s, BSD 3-clause -- tools/LTC_LICENSE).\n" % UPSTREAM)
        out.write(" * DO NOT EDIT. Regenerate: python3 tools/gen_ltc_lut.py\n")
        out.write(" *\n")
        out.write(" * Two 64x64 RGBA32F lookup tables for LTC area lights (spec 9.2):\n")
        out.write(" * LTC_MAT_TABLE = inverse-M matrix fit (a,b,c,d of the x/z block,\n")
        out.write(" * m[1][1] normalized to 1); LTC_AMP_TABLE = x: specular magnitude,\n")
        out.write(" * y: Fresnel-weighted magnitude, w: horizon-clipped sphere form\n")
        out.write(" * factor (indexed at its own uv -- owns the 1/2pi normalization).\n")
        out.write(" * Row order matches the reference texImage2D upload; sample with\n")
        out.write(" * uv = (roughness, sqrt(1-NdotV)) * 63/64 + 0.5/64.\n")
        out.write(" */\n\n")
        out.write("#ifndef _LTC_LUT_H_\n#define _LTC_LUT_H_\n\n")
        out.write("#define LTC_LUT_DIM %d\n\n" % DIM)
        emit_array(out, "LTC_MAT_TABLE", arrays[0])
        out.write("\n")
        emit_array(out, "LTC_AMP_TABLE", arrays[1])
        out.write("\n#endif // _LTC_LUT_H_\n")
    print("wrote %s (%d + %d floats)" % (DST, len(arrays[0]), len(arrays[1])))


if __name__ == "__main__":
    main()
